# portal_app.py içindeki ilgili satırları böyle güncelleyin:
# ...
<title>Akıllı Uygulamalar Portalı</title>
# ...
<h1>🚀 AKILLI UYGULAMALAR</h1>
<p>Tüm dijital araçlarınıza buradan erişebilirsiniz.</p>
# ...